export const ADD_DATA_START = 'ADD_DATA_START';
export const ADD_DATA_SUCCESS = 'ADD_DATA_SUCCESS';
export const ADD_DATA_FAIL = 'ADD_DATA_FAIL';
export const ADD_DATA_INIT = 'ADD_DATA_INIT';


export const FETCH_DATA_START = 'FETCH_DATA_START';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_DATA_FAIL = 'FETCH_DATA_FAIL';
export const SEARCH_DATA = 'SEARCH_DATA';
export const ON_INPUT_CHANGE = 'ON_INPUT_CHANGE';


export const ADD_PROFILE_START = 'ADD_PROFILE_START';
export const ADD_PROFILE_SUCCESS = 'ADD_PROFILE_SUCESS';
export const ADD_PROFILE_FAIL = 'ADD_PROFILE_FAIL';
export const ADD_PROFILE_INIT = 'ADD_PROFILE_INIT';

export const FETCH_PROFILE_START = 'FETCH_PROFILE_START';
export const FETCH_PROFILE_SUCCESS = 'FETCH_PROFILE_SUCESS';
export const FETCH_PROFILE_FAIL = 'FETCH_PROFILE_FAIL';
export const FETCH_PROFILE_INIT = 'FETCH_PROFILE_INIT';

export const ADD_SCORE_START = 'ADD_SCORE_START';
export const ADD_SCORE_SUCCESS = 'ADD_SCORE_SUCESS';
export const ADD_SCORE_FAIL = 'ADD_SCORE_FAIL';
export const ADD_SCORE_INIT = 'ADD_SCORE_INIT';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';



export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';